[package]
name = "generics_trait_life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]

name = "generics_trait_life"

path = "src/main.rs"